//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WedBanHang.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Ho")]
        public string Firstname { get; set; }

        [Display(Name = "Tên")]
        public string LastName { get; set; }
        public string Email { get; set; }

        [Display(Name = "Mat khau")]
        public string Password { get; set; }
        [Display(Name = "Có phai Admin không ?")]
        public Nullable<bool> IsAdmin { get; set; }
    }
}
